[package]
name = "raytracer"
version = "0.1.0"
authors = ["Dennis Sprokholt"]
edition = "2019"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.54"
roots        = "0.0.4"

[profile.release]
lto = true

[profile.dev]
lto = true
opt-level = 3
